### ISSUE TITLE
Riak 1.4 rpm -- sudo tty error on boot

### ISSUE THREAD

**Issue by mk1s** [basho/node_package#72]
# Riak 1.4 rpm won't start on bootup, with 'sorry, you must have a tty to run sudo' message
#### Discovery

A customer filed a ticket attempting to build a Riak-CS test setup with Riak 1.4.  The host was CentOS 6.4 and the packages were Riak-ee-1.4, Riak-cs-ee-1.3.1, and latest Stanchion.  Each service was properly added to startup via `service` command.  Riak was unable to start at boot, outputting `sorry, you must have a tty to run sudo`.  Customer was advised to disable `requiretty` and Riak as well as dependent Riak-CS services started successfully on boot.
#### Temporary Workaround
- Disable `requiretty` in `/etc/sudoers`
#### Tested Platforms / RPMs
- CentOS 5.9 [riak-ee-1.4.0-1.el5.x86_64.rpm]
- CentOS 6.3 [riak-ee1.4.0-1.el6.x86_64.rpm, riak-1.4.0-1.el6.x86_64.rpm]
- CentOS 6.4 [riak-ee1.4.0-1.el6.x86_64.rpm, riak-1.4.0-1.el6.x86_64.rpm]
#### Diagnostic Steps

Test VMs were created for the above mentioned platforms and rpms.  Each VM was cloned from a minimal CentOS install. RPMs were installed , the host was rebooted and udev was monitored for the Riak service to fail.  Temporary workaround was tested for each host successfully.  Additional attempts at other workarounds where to adjust the sudoers defaults for the riak user, `Defaults:riak !requiretty`, which had no effect.

**Comment by jaredmorrow** [comment]
According to @mk1s this is now fixed.

**Comment by uberbrady** [comment]
That's great - but where is it? I just installed the latest via RPM and the bug is still there.

How is it fixed? Did you guys replace sudo with su? Is there a commit that fixed it that we can see?

Is it expected in 1.4.2? If so, when can we expect that (roughly, of course)?

**Comment by jaredmorrow** [comment]
@uberbrady so I was never able to reproduce it, and today @mk1s told me Riak 1.4.1 fixed his issue.  We never got rid of `sudo`, but some issues with how we treated `service` calls was fixed along the way.  

Since you are still seeing this problem in Riak 1.4.1, can you give me some more information?  Do other apps work fine with `sudo` for you?  Does the init.d script for riak work fine for you outside of `service` calls?

Any information would be very welcome.

**Comment by jaredmorrow** [comment]
Reopening due to @uberbrady still seeing issue on riak 1.4.1

**Comment by mk1s** [comment]
@uberbrady I just retested both our Enterprise and Open Source 1.4.1 packages on a vanilla CentOS 6.4 and the issue does not manifest.  Please provide additional information regarding your OS version, sudo and environment settings.

**Comment by uberbrady** [comment]
Sure, I'll spin you up a box and get you what you need.

**Comment by uberbrady** [comment]
AWS Linux release 2013.03 (stock, unmodified)

followed instructions to install via RPM:

``` sh
yum -y install http://yum.basho.com/gpg/basho-release-6-1.noarch.rpm

yum -y install riak

/sbin/chkconfig --list|grep riak # nothing shows up here

/sbin/chkconfig --add riak # *NOW* it shows up - is turned on for runlevel 3

ulimit -n 999999 # otherwise it's going to yell at me about my file limit, I'm logged in as ec2-user
service riak start # it starts.

# I stop instance, and then restart it

ps auxwwwwww|grep riak #nothing shows up
```

The console log (I can fetch via web GUI) says:

```

Starting riak: sudo: sorry, you must have a tty to run sudo
[FAILED]

```

Workaround is I can disable 'requiretty' in /etc/sudoers. But I don't want to do that.

Or - if that's just gonna be how that's gonna be, you guys need to add a FAQ entry or something, because it's going to bite more people than just me. I lost a moderate chunk of time to this. (IMHO, you _should_ be using su -c instead of sudo - sudo is for normal people to become root and do rootey things, su is for root to become other people and do their mundane things).

Version:

`rpm -qa|grep riak
riak-1.4.1-1.el6.x86_64`

**Comment by jaredmorrow** [comment]
So looking into this, you can disable the requiretty setting for just the riak user, rather than all users like:

`Defaults:riak   !requiretty`

Regarding sudo v. su, we've discussed this in the past, and there are some other reasons outside of just privilege to use sudo over su, mostly in how they handle passing environmental variables and shell settings to the new session. `su` uses the shell settings of the user being switched to run the commands, where `sudo` uses the shell settings of the caller to run the command.  It doesn't mean it is impossible to use `su` rather than `sudo`, but it is a lot more work than it seems to switch it out and have it work on all platforms equally.

**Comment by NorSoulx** [comment]
#Centos 6.3 (Azure image):

This did not work for me - Riak would not start on boot with this:

> Defaults:riak !requiretty

However, setting it for user 'root' worked though. Created this file and now Riak starts on boot. 

> sudo visudo -f /etc/sudoers.d/riak 
> Defaults:root !requiretty

**Comment by ghost** [comment]
I tested it on Riak Enterprise 1.4.2.
However Riak would not start on boot.
Workaround is still Disable requiretty in /etc/sudoers.

**Comment by lukebakken** [comment]
A suggestion - if the user running the `riak` or `riak-admin` script is `root`, use `su` to switch to the `riak` user, and if not `root`, use `sudo`

I believe that using `su -l` (login) will pass the necessary environment (`HOME` seems to be the most important variable).

**Comment by jaredmorrow** [comment]
In the solaris/bsd world `su -` would be the same as `su <user> -l` without introducing a syntax difference b/w linux and solaris.  Post 2.0 we should do some testing for this.  When the scripts were first written `su` did not work, but that knowledge of "why not?" has since left.

**Comment by runesl** [comment]
The issue remains, but the following workaround worked for me:

```
sudo visudo -f /etc/sudoers.d/riak
Defaults:root !requiretty
```

```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.3 (Santiago)
# This is a "SLES Expanded Support platform release 6.3"
# The above "Red Hat Enterprise Linux Server" string is only used to 
# keep software compatibility.
```

**Comment by jaredmorrow** [comment]
Fixed in https://github.com/basho/node_package/pull/126

**Comment by megahall** [comment]
This problem is still happening for me using the following RPMs, CentOS 6.5:

```
[root@ts-optic ~]# rpm -qa | egrep -i 'riak|riak-cs|stanchion'
riak-1.4.9-1.el6.x86_64
riak-cs-1.4.5-1.el6.x86_64
stanchion-1.4.3-1.el6.x86_64
[root@ts-optic ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)
[root@ts-optic ~]#
```

**Comment by jaredmorrow** [comment]
This took a major change switching from sudo to su.  It is fixed in Riak
2.0.
